193AddedPD_VERIFIED column
bcgov/SIMS pull request #236
Opened 2021-02-23 23:25 UTC by 2011sandeepraj

Added pd_verified to the database

2021-02-23 23:59 UTC, andrewsignori-aot commented on docs/howto/db-migration.md
> +5. If applicable Add the sql that is intended to be run using
I would recommend removing the "If applicable". We should always add a rollback. Not adding would be a major exception scenario.

2021-02-24 00:01 UTC, andrewsignori-aot commented on docs/howto/db-migration.md
> +   queryRunner.query() method inside down method. This will be run when database is being wiped out.
The rollback runs when the migration is "rolled back", not necessarily during a database cleanup.

2021-02-24 00:03 UTC, andrewsignori-aot commented on docs/howto/db-migration.md
> +   $ make local-clean
That is only necessary if we want to test all the migrations at once. To test the particular one, we can just run the application with the "make-local".

2021-02-24 00:04 UTC, andrewsignori-aot commented on sources/packages/api/src-sql/StudentPDVerified/Add-StudentPDVerified.sql
> +-- -- Removing the dummy constraint created just to allow us
Please remove the comment code.

2021-02-24 00:09 UTC, andrewsignori-aot commented on sources/packages/api/src-sql/StudentPDVerified/Add-StudentPDVerified.sql
> +ALTER TABLE students
I believe that there is a problem with the syntax.
The correct command would be:
ALTER TABLE students
    ADD COLUMN IF NOT EXISTS pd_verified BOOLEAN;

2021-02-24 00:12 UTC, andrewsignori-aot requested changes
Really nice working creating the documentation 👍 
Please take a look at the comments and ensure that the migration script is working as expected.

2021-02-24 00:20 UTC, andrewsignori-aot approved these changes
After a chat with @2011sandeepraj he updated the "up" script with the correct file and it looks good, hence approving this PR.

2021-02-24 14:12 UTC, fwpushan approved these changes

2021-02-24 17:32 UTC, merged