Updated JSON and data field change in NOA
bcgov/SIMS pull request #600
Opened 2021-07-29 20:01 UTC by guru-aot

2021-07-29 20:35 UTC, andrewsignori-aot requested changes
I noticed that the json on databse is represented as below:
```
{
    "weeks": 52,
    "total_federal_award": 22893,
    "total_provincial_award": 2656.8911627906964,
    "federal_assessment_need": 4642.227906976743,
    "provincial_assessment_need": 4642.227906976743
}
```
Please rename the variable to be in accordance with the others that we have in SIMS DB and also in the form definitions (e.g. provincialAssessmentNeed).

Why the structure above is not being used as a form data directly?
Instead of having the custom code below
![image](https://user-images.githubusercontent.com/61259237/127562006-d61c86f2-3d17-
4a0d-8d7a-b717e6fead7d.png)

we could be accessing the form data directly (e.g. data.provincialAssessmentNeed).
I would recommend using custom code only when it is needed. I am not convinced that this would be the case.
IMO, we should try to keep the form definition as dry as possible.

2021-07-29 20:42 UTC, guru-aot commented
> provincialAssessmentNeed

2021-07-29 23:40 UTC, andrewsignori-aot commented on sources/packages/forms/src/form-definitions/noticeofassessment.json
> +          "calculateValue": "let eligibleAmount=JSON.stringify(data.totalFederalAward+data.totalProvincialAward);\nvalue='<h1><B>You are eligible to receive $'+eligibleAmount+' for '+data.weeks+' wee
Is there a reason to keep the JSON.stringify here?

2021-07-29 23:55 UTC, andrewsignori-aot approved these changes
👍

2021-07-30 15:13 UTC, abschwenker approved these changes

2021-07-30 15:35 UTC, merged

2021-07-30 15:36 UTC, ann-aot approved these changes